#!/usr/bin/env python3
"""
Common substrings and words from avesso_da_pele.txt.
This file is automatically generated by find_common_substrings.py.
"""

# Common words
COMMON_WORDS = [
    # 1832 occurrences
    'QUE',
    # 619 occurrences
    'PARA',
    # 532 occurrences
    'COM',
    # 429 occurrences
    'UMA',
    # 426 occurrences
    'ELA',
    # 392 occurrences
    'ERA',
    # 359 occurrences
    'MINHA',
    # 338 occurrences
    'MAS',
    # 320 occurrences
    'POR',
    # 291 occurrences
    'MAIS',
    # 268 occurrences
    'SUA',
    # 264 occurrences
    'QUANDO',
    # 255 occurrences
    'PORQUE',
    # 253 occurrences
    'TINHA',
    # 247 occurrences
    'ESTAVA',
    # 231 occurrences
    'ELE',
    # 216 occurrences
    'DISSE',
    # 205 occurrences
    'COMO',
    # 203 occurrences
    'FOI',
    # 190 occurrences
    'ISSO',
    # 181 occurrences
    'DEPOIS',
    # 163 occurrences
    'SEU',
    # 138 occurrences
    'CASA',
    # 134 occurrences
    'MESMO',
    # 131 occurrences
    'TUDO',
    # 129 occurrences
    'HAVIA',
    # 127 occurrences
    'ELES',
    # 124 occurrences
    'VIDA',
    # 123 occurrences
    'DIA',
    # 121 occurrences
    'SER',
    # 120 occurrences
    'AINDA',
    # 115 occurrences
    'MUITO',
    # 114 occurrences
    'ANOS',
    # 112 occurrences
    'TER',
    # 109 occurrences
    'SOBRE',
    # 107 occurrences
    'QUERIA',
    # 102 occurrences
    'SEMPRE',
    # 100 occurrences
    'NUNCA',
    # 96 occurrences
    'DOS',
    # 96 occurrences
    'NADA',
    # 96 occurrences
    'DELA',
    # 95 occurrences
    'COISAS',
    # 94 occurrences
    'ASSIM',
    # 92 occurrences
    'FAZER',
    # 85 occurrences
    'BEM',
    # 84 occurrences
    'NOS',
    # 83 occurrences
    'SABIA',
    # 83 occurrences
    'AQUILO',
    # 78 occurrences
    'APENAS',
    # 77 occurrences
    'POUCO',
]

# Common substrings by length
COMMON_SUBSTRINGS = {
    5: [
        # 557 occurrences
        'EVOCE',
        # 398 occurrences
        'MINHA',
        # 397 occurrences
        'VOCES',
        # 375 occurrences
        'STAVA',
        # 368 occurrences
        'INHAM',
        # 336 occurrences
        'ESTAV',
        # 326 occurrences
        'OVOCE',
        # 312 occurrences
        'ORQUE',
        # 303 occurrences
        'TINHA',
        # 303 occurrences
        'NHAMA',
        # 300 occurrences
        'PORQU',
        # 292 occurrences
        'HAMAE',
        # 286 occurrences
        'AQUEL',
        # 273 occurrences
        'UEVOC',
        # 266 occurrences
        'QUEVO',
        # 265 occurrences
        'UANDO',
        # 264 occurrences
        'QUAND',
        # 247 occurrences
        'AVOCE',
        # 242 occurrences
        'DISSE',
        # 187 occurrences
        'EPOIS',
    ],
    6: [
        # 335 occurrences
        'ESTAVA',
        # 302 occurrences
        'INHAMA',
        # 296 occurrences
        'PORQUE',
        # 294 occurrences
        'MINHAM',
        # 292 occurrences
        'NHAMAE',
        # 273 occurrences
        'UEVOCE',
        # 264 occurrences
        'QUANDO',
        # 263 occurrences
        'QUEVOC',
        # 182 occurrences
        'DEPOIS',
        # 149 occurrences
        'EVOCES',
        # 144 occurrences
        'AQUELE',
        # 143 occurrences
        'AMINHA',
        # 142 occurrences
        'AQUELA',
        # 134 occurrences
        'QUENAO',
        # 134 occurrences
        'EESTAV',
        # 123 occurrences
        'QUERIA',
        # 123 occurrences
        'EDISSE',
        # 119 occurrences
        'VOCENA',
        # 118 occurrences
        'OCENAO',
        # 117 occurrences
        'VOCESE',
    ],
    7: [
        # 293 occurrences
        'MINHAMA',
        # 292 occurrences
        'INHAMAE',
        # 263 occurrences
        'QUEVOCE',
        # 134 occurrences
        'EESTAVA',
        # 118 occurrences
        'VOCENAO',
        # 104 occurrences
        'PERGUNT',
        # 103 occurrences
        'DISSEQU',
        # 103 occurrences
        'ISSEQUE',
        # 97 occurrences
        'ESTAVAM',
        # 87 occurrences
        'PROFESS',
        # 87 occurrences
        'ROFESSO',
        # 87 occurrences
        'OFESSOR',
        # 79 occurrences
        'QUEESTA',
        # 78 occurrences
        'AMINHAM',
        # 76 occurrences
        'ACONTEC',
        # 75 occurrences
        'EMINHAM',
        # 74 occurrences
        'SCOISAS',
        # 73 occurrences
        'ASCOISA',
        # 72 occurrences
        'NDOVOCE',
        # 69 occurrences
        'VERDADE',
    ],
    8: [
        # 291 occurrences
        'MINHAMAE',
        # 103 occurrences
        'DISSEQUE',
        # 87 occurrences
        'PROFESSO',
        # 87 occurrences
        'ROFESSOR',
        # 78 occurrences
        'AMINHAMA',
        # 74 occurrences
        'EMINHAMA',
        # 73 occurrences
        'ASCOISAS',
        # 68 occurrences
        'OQUEVOCE',
        # 68 occurrences
        'MADALENA',
        # 66 occurrences
        'ANDOVOCE',
        # 63 occurrences
        'AVERDADE',
        # 62 occurrences
        'QUANDOVO',
        # 61 occurrences
        'UANDOVOC',
        # 61 occurrences
        'QUEESTAV',
        # 61 occurrences
        'UEESTAVA',
        # 59 occurrences
        'EDISSEQU',
        # 59 occurrences
        'CONSEGUI',
        # 59 occurrences
        'OMINHAMA',
        # 58 occurrences
        'NOENTANT',
        # 58 occurrences
        'OENTANTO',
    ],
    9: [
        # 87 occurrences
        'PROFESSOR',
        # 77 occurrences
        'AMINHAMAE',
        # 74 occurrences
        'EMINHAMAE',
        # 61 occurrences
        'QUANDOVOC',
        # 61 occurrences
        'UANDOVOCE',
        # 61 occurrences
        'QUEESTAVA',
        # 59 occurrences
        'EDISSEQUE',
        # 59 occurrences
        'OMINHAMAE',
        # 58 occurrences
        'NOENTANTO',
        # 54 occurrences
        'NAVERDADE',
        # 54 occurrences
        'SAHARIENN',
        # 54 occurrences
        'AHARIENNE',
        # 53 occurrences
        'PERGUNTOU',
        # 51 occurrences
        'MINHAMAEE',
        # 46 occurrences
        'VOCETINHA',
        # 44 occurrences
        'RESPONDEU',
        # 43 occurrences
        'APRIMEIRA',
        # 42 occurrences
        'VOCEESTAV',
        # 42 occurrences
        'OCEESTAVA',
        # 41 occurrences
        'ASPESSOAS',
    ],
    10: [
        # 61 occurrences
        'QUANDOVOCE',
        # 54 occurrences
        'SAHARIENNE',
        # 42 occurrences
        'VOCEESTAVA',
        # 39 occurrences
        'PORTOALEGR',
        # 39 occurrences
        'ORTOALEGRE',
        # 37 occurrences
        'OPROFESSOR',
        # 33 occurrences
        'NAOCONSEGU',
        # 31 occurrences
        'AOCONSEGUI',
        # 31 occurrences
        'EPERGUNTOU',
        # 30 occurrences
        'QUEMINHAMA',
        # 30 occurrences
        'UEMINHAMAE',
        # 29 occurrences
        'APRIMEIRAV',
        # 29 occurrences
        'PRIMEIRAVE',
        # 29 occurrences
        'RIMEIRAVEZ',
        # 26 occurrences
        'DIZENDOQUE',
        # 25 occurrences
        'UMAESPECIE',
        # 25 occurrences
        'MAESPECIED',
        # 25 occurrences
        'AESPECIEDE',
        # 25 occurrences
        'ENAOQUERIA',
        # 25 occurrences
        'ERESPONDEU',
    ],
    11: [
        # 39 occurrences
        'PORTOALEGRE',
        # 31 occurrences
        'NAOCONSEGUI',
        # 30 occurrences
        'QUEMINHAMAE',
        # 29 occurrences
        'APRIMEIRAVE',
        # 29 occurrences
        'PRIMEIRAVEZ',
        # 25 occurrences
        'UMAESPECIED',
        # 25 occurrences
        'MAESPECIEDE',
        # 22 occurrences
        'ACONTECEQUE',
        # 22 occurrences
        'ASAHARIENNE',
        # 20 occurrences
        'DISSEQUENAO',
        # 19 occurrences
        'VOCENAOSABI',
        # 19 occurrences
        'OCENAOSABIA',
        # 19 occurrences
        'PERCEBEUQUE',
        # 19 occurrences
        'EVOCEESTAVA',
        # 19 occurrences
        'QUEVOCEESTA',
        # 19 occurrences
        'VOCEPENSAVA',
        # 18 occurrences
        'OQUANDOVOCE',
        # 18 occurrences
        'EPORTOALEGR',
        # 18 occurrences
        'AOCONSEGUIA',
        # 17 occurrences
        'DEPORTOALEG',
    ],
    12: [
        # 29 occurrences
        'APRIMEIRAVEZ',
        # 25 occurrences
        'UMAESPECIEDE',
        # 19 occurrences
        'VOCENAOSABIA',
        # 18 occurrences
        'EPORTOALEGRE',
        # 18 occurrences
        'NAOCONSEGUIA',
        # 17 occurrences
        'DEPORTOALEGR',
        # 17 occurrences
        'RESPONDEUQUE',
        # 15 occurrences
        'PRIMEIRAVEZQ',
        # 15 occurrences
        'RIMEIRAVEZQU',
        # 15 occurrences
        'IMEIRAVEZQUE',
        # 15 occurrences
        'QUEVOCETINHA',
        # 15 occurrences
        'UEVOCEESTAVA',
        # 15 occurrences
        'VOCERESPONDE',
        # 14 occurrences
        'NESSEMOMENTO',
        # 14 occurrences
        'QUENAOQUERIA',
        # 14 occurrences
        'SIMPLESMENTE',
        # 14 occurrences
        'VOCESESTAVAM',
        # 14 occurrences
        'QUEVOCEESTAV',
        # 14 occurrences
        'OCERESPONDEU',
        # 13 occurrences
        'MPORTOALEGRE',
    ],
    13: [
        # 17 occurrences
        'DEPORTOALEGRE',
        # 15 occurrences
        'APRIMEIRAVEZQ',
        # 15 occurrences
        'PRIMEIRAVEZQU',
        # 15 occurrences
        'RIMEIRAVEZQUE',
        # 14 occurrences
        'QUEVOCEESTAVA',
        # 14 occurrences
        'VOCERESPONDEU',
        # 13 occurrences
        'AQUELEMOMENTO',
        # 13 occurrences
        'ERESPONDEUQUE',
        # 12 occurrences
        'EMPORTOALEGRE',
        # 12 occurrences
        'QUANDOMINHAMA',
        # 12 occurrences
        'UANDOMINHAMAE',
        # 12 occurrences
        'OPROFESSOROLI',
        # 12 occurrences
        'PROFESSOROLIV',
        # 12 occurrences
        'ROFESSOROLIVE',
        # 12 occurrences
        'OFESSOROLIVEI',
        # 12 occurrences
        'FESSOROLIVEIR',
        # 12 occurrences
        'ESSOROLIVEIRA',
        # 12 occurrences
        'POSSIBILIDADE',
        # 11 occurrences
        'NAVERDADEVOCE',
        # 11 occurrences
        'PELAPRIMEIRAV',
    ],
    14: [
        # 15 occurrences
        'APRIMEIRAVEZQU',
        # 15 occurrences
        'PRIMEIRAVEZQUE',
        # 12 occurrences
        'QUANDOMINHAMAE',
        # 12 occurrences
        'OPROFESSOROLIV',
        # 12 occurrences
        'PROFESSOROLIVE',
        # 12 occurrences
        'ROFESSOROLIVEI',
        # 12 occurrences
        'OFESSOROLIVEIR',
        # 12 occurrences
        'FESSOROLIVEIRA',
        # 11 occurrences
        'PELAPRIMEIRAVE',
        # 11 occurrences
        'ELAPRIMEIRAVEZ',
        # 10 occurrences
        'OQUEESTAVAACON',
        # 10 occurrences
        'QUEESTAVAACONT',
        # 10 occurrences
        'UEESTAVAACONTE',
        # 10 occurrences
        'EESTAVAACONTEC',
        # 10 occurrences
        'ESTAVAACONTECE',
        # 10 occurrences
        'STAVAACONTECEN',
        # 10 occurrences
        'TAVAACONTECEND',
        # 10 occurrences
        'AVAACONTECENDO',
        # 10 occurrences
        'NAQUELEMOMENTO',
        # 10 occurrences
        'SUFICIENTEPARA',
    ],
    15: [
        # 15 occurrences
        'APRIMEIRAVEZQUE',
        # 12 occurrences
        'OPROFESSOROLIVE',
        # 12 occurrences
        'PROFESSOROLIVEI',
        # 12 occurrences
        'ROFESSOROLIVEIR',
        # 12 occurrences
        'OFESSOROLIVEIRA',
        # 11 occurrences
        'PELAPRIMEIRAVEZ',
        # 10 occurrences
        'OQUEESTAVAACONT',
        # 10 occurrences
        'QUEESTAVAACONTE',
        # 10 occurrences
        'UEESTAVAACONTEC',
        # 10 occurrences
        'EESTAVAACONTECE',
        # 10 occurrences
        'ESTAVAACONTECEN',
        # 10 occurrences
        'STAVAACONTECEND',
        # 10 occurrences
        'TAVAACONTECENDO',
        # 9 occurrences
        'FOIAPRIMEIRAVEZ',
        # 9 occurrences
        'OIAPRIMEIRAVEZQ',
        # 9 occurrences
        'IAPRIMEIRAVEZQU',
        # 8 occurrences
        'OSUFICIENTEPARA',
        # 7 occurrences
        'PRIMEIRAVEZQUEV',
        # 7 occurrences
        'RIMEIRAVEZQUEVO',
        # 7 occurrences
        'IMEIRAVEZQUEVOC',
    ],
}

# Potential known plaintext segments for attacks
KNOWN_PLAINTEXT_SEGMENTS = [
    # Length 15, 15 occurrences
    'APRIMEIRAVEZQUE',
    # Length 14, 15 occurrences
    'APRIMEIRAVEZQU',
    # Length 13, 17 occurrences
    'DEPORTOALEGRE',
    # Length 12, 29 occurrences
    'APRIMEIRAVEZ',
    # Length 11, 39 occurrences
    'PORTOALEGRE',
    # Length 10, 61 occurrences
    'QUANDOVOCE',
    # Length 9, 87 occurrences
    'PROFESSOR',
    # Length 8, 291 occurrences
    'MINHAMAE',
    # Length 7, 293 occurrences
    'MINHAMA',
    # Length 6, 335 occurrences
    'ESTAVA',
    # Length 5, 557 occurrences
    'EVOCE',
    # Word, 359 occurrences
    'MINHA',
]
