#!/usr/bin/env python3
"""
Known plaintext segments from avesso_da_pele.txt.
This file is automatically generated by find_common_substrings.py.
"""

# Potential known plaintext segments for Hill cipher breaking
KNOWN_PLAINTEXT_SEGMENTS = [
    'SENTRARAMNOCARROEFORAMEMBORA',
    'RASGATASMAISQUENTESDACIDADE',
    'SENTRARAMNOCARROEFORAMEMBOR',
    'ENTRARAMNOCARROEFORAMEMBORA',
    'RASGATASMAISQUENTESDACIDAD',
    'ASGATASMAISQUENTESDACIDADE',
    'OFAZUMGRANDEESFORCOPARANAO',
    'SENTRARAMNOCARROEFORAMEMBO',
    'ENTRARAMNOCARROEFORAMEMBOR',
    'NTRARAMNOCARROEFORAMEMBORA',
    'MINHA',
    'QUANDO',
    'PORQUE',
    'TINHA',
    'ESTAVA',
    'DISSE',
    'VOCE',
    'AQUELE',
    'SEMPRE',
    'MINHAMAE',
    'PROFESSOR',
    'ESCOLA',
    'ALUNOS',
    'POLICIA',
    'RASKOLNIKOV',
]

# Common words
COMMON_WORDS = [
    # 1832 occurrences
    'QUE',
    # 619 occurrences
    'PARA',
    # 532 occurrences
    'COM',
    # 429 occurrences
    'UMA',
    # 426 occurrences
    'ELA',
    # 392 occurrences
    'ERA',
    # 359 occurrences
    'MINHA',
    # 338 occurrences
    'MAS',
    # 320 occurrences
    'POR',
    # 291 occurrences
    'MAIS',
    # 268 occurrences
    'SUA',
    # 264 occurrences
    'QUANDO',
    # 255 occurrences
    'PORQUE',
    # 253 occurrences
    'TINHA',
    # 247 occurrences
    'ESTAVA',
    # 231 occurrences
    'ELE',
    # 216 occurrences
    'DISSE',
    # 205 occurrences
    'COMO',
    # 203 occurrences
    'FOI',
    # 190 occurrences
    'ISSO',
    # 181 occurrences
    'DEPOIS',
    # 163 occurrences
    'SEU',
    # 138 occurrences
    'CASA',
    # 134 occurrences
    'MESMO',
    # 131 occurrences
    'TUDO',
    # 129 occurrences
    'HAVIA',
    # 127 occurrences
    'ELES',
    # 124 occurrences
    'VIDA',
    # 123 occurrences
    'DIA',
    # 121 occurrences
    'SER',
    # 120 occurrences
    'AINDA',
    # 115 occurrences
    'MUITO',
    # 114 occurrences
    'ANOS',
    # 112 occurrences
    'TER',
    # 109 occurrences
    'SOBRE',
    # 107 occurrences
    'QUERIA',
    # 102 occurrences
    'SEMPRE',
    # 100 occurrences
    'NUNCA',
    # 96 occurrences
    'DOS',
    # 96 occurrences
    'NADA',
    # 96 occurrences
    'DELA',
    # 95 occurrences
    'COISAS',
    # 94 occurrences
    'ASSIM',
    # 92 occurrences
    'FAZER',
    # 85 occurrences
    'BEM',
    # 84 occurrences
    'NOS',
    # 83 occurrences
    'SABIA',
    # 83 occurrences
    'AQUILO',
    # 78 occurrences
    'APENAS',
    # 77 occurrences
    'POUCO',
]

# Common substrings by length
COMMON_SUBSTRINGS = {
    5: [
        # 557 occurrences
        'EVOCE',
        # 398 occurrences
        'MINHA',
        # 397 occurrences
        'VOCES',
        # 375 occurrences
        'STAVA',
        # 368 occurrences
        'INHAM',
        # 336 occurrences
        'ESTAV',
        # 326 occurrences
        'OVOCE',
        # 312 occurrences
        'ORQUE',
        # 303 occurrences
        'TINHA',
        # 303 occurrences
        'NHAMA',
    ],
    6: [
        # 335 occurrences
        'ESTAVA',
        # 302 occurrences
        'INHAMA',
        # 296 occurrences
        'PORQUE',
        # 294 occurrences
        'MINHAM',
        # 292 occurrences
        'NHAMAE',
        # 273 occurrences
        'UEVOCE',
        # 264 occurrences
        'QUANDO',
        # 263 occurrences
        'QUEVOC',
        # 182 occurrences
        'DEPOIS',
        # 149 occurrences
        'EVOCES',
    ],
    7: [
        # 293 occurrences
        'MINHAMA',
        # 292 occurrences
        'INHAMAE',
        # 263 occurrences
        'QUEVOCE',
        # 134 occurrences
        'EESTAVA',
        # 118 occurrences
        'VOCENAO',
        # 104 occurrences
        'PERGUNT',
        # 103 occurrences
        'DISSEQU',
        # 103 occurrences
        'ISSEQUE',
        # 97 occurrences
        'ESTAVAM',
        # 87 occurrences
        'PROFESS',
    ],
    8: [
        # 291 occurrences
        'MINHAMAE',
        # 103 occurrences
        'DISSEQUE',
        # 87 occurrences
        'PROFESSO',
        # 87 occurrences
        'ROFESSOR',
        # 78 occurrences
        'AMINHAMA',
        # 74 occurrences
        'EMINHAMA',
        # 73 occurrences
        'ASCOISAS',
        # 68 occurrences
        'OQUEVOCE',
        # 68 occurrences
        'MADALENA',
        # 66 occurrences
        'ANDOVOCE',
    ],
    9: [
        # 87 occurrences
        'PROFESSOR',
        # 77 occurrences
        'AMINHAMAE',
        # 74 occurrences
        'EMINHAMAE',
        # 61 occurrences
        'QUANDOVOC',
        # 61 occurrences
        'UANDOVOCE',
        # 61 occurrences
        'QUEESTAVA',
        # 59 occurrences
        'EDISSEQUE',
        # 59 occurrences
        'OMINHAMAE',
        # 58 occurrences
        'NOENTANTO',
        # 54 occurrences
        'NAVERDADE',
    ],
    10: [
        # 61 occurrences
        'QUANDOVOCE',
        # 54 occurrences
        'SAHARIENNE',
        # 42 occurrences
        'VOCEESTAVA',
        # 39 occurrences
        'PORTOALEGR',
        # 39 occurrences
        'ORTOALEGRE',
        # 37 occurrences
        'OPROFESSOR',
        # 33 occurrences
        'NAOCONSEGU',
        # 31 occurrences
        'AOCONSEGUI',
        # 31 occurrences
        'EPERGUNTOU',
        # 30 occurrences
        'QUEMINHAMA',
    ],
    11: [
        # 39 occurrences
        'PORTOALEGRE',
        # 31 occurrences
        'NAOCONSEGUI',
        # 30 occurrences
        'QUEMINHAMAE',
        # 29 occurrences
        'APRIMEIRAVE',
        # 29 occurrences
        'PRIMEIRAVEZ',
        # 25 occurrences
        'UMAESPECIED',
        # 25 occurrences
        'MAESPECIEDE',
        # 22 occurrences
        'ACONTECEQUE',
        # 22 occurrences
        'ASAHARIENNE',
        # 20 occurrences
        'DISSEQUENAO',
    ],
    12: [
        # 29 occurrences
        'APRIMEIRAVEZ',
        # 25 occurrences
        'UMAESPECIEDE',
        # 19 occurrences
        'VOCENAOSABIA',
        # 18 occurrences
        'EPORTOALEGRE',
        # 18 occurrences
        'NAOCONSEGUIA',
        # 17 occurrences
        'DEPORTOALEGR',
        # 17 occurrences
        'RESPONDEUQUE',
        # 15 occurrences
        'PRIMEIRAVEZQ',
        # 15 occurrences
        'RIMEIRAVEZQU',
        # 15 occurrences
        'IMEIRAVEZQUE',
    ],
    13: [
        # 17 occurrences
        'DEPORTOALEGRE',
        # 15 occurrences
        'APRIMEIRAVEZQ',
        # 15 occurrences
        'PRIMEIRAVEZQU',
        # 15 occurrences
        'RIMEIRAVEZQUE',
        # 14 occurrences
        'QUEVOCEESTAVA',
        # 14 occurrences
        'VOCERESPONDEU',
        # 13 occurrences
        'AQUELEMOMENTO',
        # 13 occurrences
        'ERESPONDEUQUE',
        # 12 occurrences
        'EMPORTOALEGRE',
        # 12 occurrences
        'QUANDOMINHAMA',
    ],
    14: [
        # 15 occurrences
        'APRIMEIRAVEZQU',
        # 15 occurrences
        'PRIMEIRAVEZQUE',
        # 12 occurrences
        'QUANDOMINHAMAE',
        # 12 occurrences
        'OPROFESSOROLIV',
        # 12 occurrences
        'PROFESSOROLIVE',
        # 12 occurrences
        'ROFESSOROLIVEI',
        # 12 occurrences
        'OFESSOROLIVEIR',
        # 12 occurrences
        'FESSOROLIVEIRA',
        # 11 occurrences
        'PELAPRIMEIRAVE',
        # 11 occurrences
        'ELAPRIMEIRAVEZ',
    ],
    15: [
        # 15 occurrences
        'APRIMEIRAVEZQUE',
        # 12 occurrences
        'OPROFESSOROLIVE',
        # 12 occurrences
        'PROFESSOROLIVEI',
        # 12 occurrences
        'ROFESSOROLIVEIR',
        # 12 occurrences
        'OFESSOROLIVEIRA',
        # 11 occurrences
        'PELAPRIMEIRAVEZ',
        # 10 occurrences
        'OQUEESTAVAACONT',
        # 10 occurrences
        'QUEESTAVAACONTE',
        # 10 occurrences
        'UEESTAVAACONTEC',
        # 10 occurrences
        'EESTAVAACONTECE',
    ],
}
