#!/usr/bin/env python3
"""
Portuguese n-gram frequencies extracted from avesso_da_pele.txt.
This file is automatically generated by extract_ngram_frequencies.py.
"""

# Letter frequencies
LETTER_FREQUENCIES = {
    'A': 0.149862,
    'B': 0.009333,
    'C': 0.039623,
    'D': 0.043771,
    'E': 0.132620,
    'F': 0.010055,
    'G': 0.010855,
    'H': 0.012345,
    'I': 0.059784,
    'J': 0.002765,
    'K': 0.000223,
    'L': 0.026170,
    'M': 0.049864,
    'N': 0.052396,
    'O': 0.102204,
    'P': 0.026938,
    'Q': 0.016302,
    'R': 0.061450,
    'S': 0.074214,
    'T': 0.040009,
    'U': 0.049543,
    'V': 0.023521,
    'W': 0.000042,
    'X': 0.001564,
    'Y': 0.000023,
    'Z': 0.004525,
}

# Top 2-grams
DIGRAMS = [
    'RA',
    'ES',
    'AS',
    'EN',
    'QU',
    'SE',
    'DE',
    'AR',
    'UE',
    'MA',
    'ER',
    'AM',
    'OS',
    'CO',
    'DO',
    'AD',
    'NT',
    'AN',
    'TA',
    'OC',
]

# Top 3-grams
TRIGRAMS = [
    'QUE',
    'OCE',
    'VOC',
    'ENT',
    'ARA',
    'AVA',
    'COM',
    'NAO',
    'AMA',
    'ADE',
    'INH',
    'NHA',
    'PAR',
    'AQU',
    'ELA',
    'ERA',
    'NTE',
    'NDO',
    'SSE',
    'POR',
]

# Top 4-grams
QUADGRAMS = [
    'VOCE',
    'INHA',
    'PARA',
    'AQUE',
    'EVOC',
    'ANDO',
    'OQUE',
    'ESTA',
    'TAVA',
    'ENTE',
    'EQUE',
    'RQUE',
    'MINH',
    'OCES',
    'ENAO',
    'ENTA',
    'MENT',
    'QUEE',
    'STAV',
    'NHAM',
]

# Top 5-grams
PENTAGRAMS = [
    'EVOCE',
    'MINHA',
    'VOCES',
    'STAVA',
    'INHAM',
    'ESTAV',
    'OVOCE',
    'ORQUE',
    'TINHA',
    'NHAMA',
    'PORQU',
    'HAMAE',
    'AQUEL',
    'UEVOC',
    'QUEVO',
    'UANDO',
    'QUAND',
    'AVOCE',
    'DISSE',
    'EPOIS',
]

# Dictionary for use in frequency analyzer
COMMON_NGRAMS = {
    2: ['RA', 'ES', 'AS', 'EN', 'QU', 'SE', 'DE', 'AR', 'UE', 'MA', 'ER', 'AM', 'OS', 'CO', 'DO', 'AD', 'NT', 'AN', 'TA', 'OC'],
    3: ['QUE', 'OCE', 'VOC', 'ENT', 'ARA', 'AVA', 'COM', 'NAO', 'AMA', 'ADE', 'INH', 'NHA', 'PAR', 'AQU', 'ELA', 'ERA', 'NTE', 'NDO', 'SSE', 'POR'],
    4: ['VOCE', 'INHA', 'PARA', 'AQUE', 'EVOC', 'ANDO', 'OQUE', 'ESTA', 'TAVA', 'ENTE', 'EQUE', 'RQUE', 'MINH', 'OCES', 'ENAO', 'ENTA', 'MENT', 'QUEE', 'STAV', 'NHAM'],
    5: ['EVOCE', 'MINHA', 'VOCES', 'STAVA', 'INHAM', 'ESTAV', 'OVOCE', 'ORQUE', 'TINHA', 'NHAMA', 'PORQU', 'HAMAE', 'AQUEL', 'UEVOC', 'QUEVO', 'UANDO', 'QUAND', 'AVOCE', 'DISSE', 'EPOIS'],
}
